---
title: "Proyecto Final"
author: "Inma Latorre"
date: "11/12/2019"
output: 
  html_document: 
    toc: true 
    toc_float:
      collapsed: false
      Smooth_scroll: false
    theme: united
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Curso de iniciación a R

## Contenido

1. Una sección en el que indiquen dos páginas con recursos sobre expresiones regulares discutidas (cuál es mejor, cuál es peor, por qué).
1. Una sección en la que se indiquen dos páginas con recursos sobre markdown y discutirlas como antes.
1. Una sección en la que se carguen, estudien, representen gráficamente unos datos de tu elección. No se trata de hacer un análisis estadístico (está fuera de alcance) pero sí un estudio descriptivo mínimo de los aspectos más relevantes de los datos. Este estudio tiene que contener, al menos:

    1. Un gráfico generado con `ggplot2`.
    2. Una tabla.

Y finalmente, por supuesto, el documento tiene que tener su tabla de contenidos y una estructura y texto... propia de un documento similar a todos los documentos normales que circulan por el mundo. 

## 1. Expresiones Regulares

Las expresiones regulares (también llamadas _"regex"_ o _"regexp"_) definen patrones que pueden compararse con una cadena . Escriba ```?regex``` para la documentación oficial de R y consulte Regex Docs para obtener más detalles. El 'gotcha' más importante que no se aprenderá en la regex / temas de SO es que la mayoría de las funciones de R-regex necesitan el uso de barras invertidas emparejadas para escapar en un parámetro de pattern .

### 1.1 lo que sea

### 1.2. lo otro que sea

## 2. R Markdown

### 2.1 Recurso Markdown 1

### 2.2 Recurso Markdown 2

## 3. Estudio gráfico 




